version: '3.9'

networks:
  data-stream:
    external:
      name: data-stream
services:
  spark:
    image: vasistapolali/spark:3.4
    networks:
      - data-stream
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_NO_DAEMONIZE=false
      - SPARK_CONNECT=true
    ports:
      - '5000:8080'
      - '7077:7077'
      - '4040:4040'
      - '15002:15002'
    volumes:
      - /mnt:/home
  spark-worker:
    image: vasistapolali/spark:3.4
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - data-stream
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8081:8081'
    volumes:
      - /mnt:/home

