version: '3.9'

networks:
  data-stream:
    external:
      name: data-stream

services:
  postgres:
    image: postgres:13
    networks:
      - data-stream
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
  airflow:
    image: vasistapolali/airflow:2.6.2
    networks:
      - data-stream
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://test:test@postgres/test
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - /mnt/airflow/dags:/usr/local/airflow/dags
      - /mnt/airflow/logs:/usr/local/airflow/logs
      - /mnt/airflow/config:/usr/local/airflow/config
      - /mnt/airflow/plugins:/usr/local/airflow/plugins
      - /mnt/airflow/scripts:/usr/local/airflow/scripts
      - /mnt/spark_checkpoint/:/tmp/spark_checkpoint
    ports:
      - "8080:18080"
