version: "3.9"

networks:
 ingress-net:
   external:
     name: data-stream

services:
  kafka-1:
    image: bitnami/kafka:3.3.2-debian-11-r40
    networks:
      - ingress-net
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=5Yr1SIgYQz-b-dgRabWx4g
      - BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - "./kafka-1-data:/bitnami/kafka"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - ingress-net
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
      - KAFKA_CLUSTERS_0_METRICS_PORT=9997
      - DYNAMIC_CONFIG_ENABLED='true'
    ports:
      - '5001:8080'


