version: "3.9"

networks:
 ingress-net:
   external:
     name: data-stream
services:
  kafka-1:
    image: bitnami/kafka:3.3.2-debian-11-r40
    networks:
      - ingress-net
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - "/mnt/kafka-1-data:/bitnami"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - ingress-net
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
      - KAFKA_CLUSTERS_0_METRICS_PORT=9997
      - DYNAMIC_CONFIG_ENABLED='true'
    ports:
      - '5001:8080'


